#!/usr/bin/env bash
#
# Verifies requirements before releasing a package
#
set -e

# Can only release from a git repo
if ! git rev-parse 2>/dev/null; then
  echo >&2 "fatal: can't release unless a git repo"
  exit 1
fi

# Can only release if not dirty
if ! git diff --quiet; then
  echo >&2 "fatal: can't release when dirty worktree"
  git diff --name-only >&2
  exit 1
fi

# Can only release if we have a tag on the current commit.
if ! git describe --tags --exact-match > /dev/null; then
  echo >&2 "fatal: release requires tag"
  exit 1
fi
